# Linear Regression

In [572]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn 
import warnings

In [573]:
sklearn.__version__

'1.5.0'

In [574]:
# Row Data
df = pd.read_csv('Used_Bikes.csv')
df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
32643,Hero Passion Pro 100cc,39000.0,Delhi,22000.0,First Owner,4.0,100.0,Hero
32644,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32645,Bajaj Avenger Street 220,60000.0,Delhi,20373.0,First Owner,6.0,220.0,Bajaj
32646,Hero Super Splendor 125cc,15600.0,Jaipur,84186.0,First Owner,16.0,125.0,Hero
32647,Bajaj Pulsar 150cc,22000.0,Pune,60857.0,First Owner,13.0,150.0,Bajaj

In [575]:
df.info() # it defines no. of rows and colouns in a dataset

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32648 entries, 0 to 32647
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   bike_name   32648 non-null  object
 1   price       32648 non-null  float64
 2   city        32648 non-null  object
 3   kms_driven  32648 non-null  float64
 4   owner       32648 non-null  object
 5   age         32648 non-null  float64
 6   power       32648 non-null  float64
 7   brand       32648 non-null  object
dtypes: float64(4), object(4)
memory usage: 2.0+ MB

In [576]:
## for duplicates values
df.duplicated().sum()

25324

In [577]:
df.drop_duplicates(inplace=True)
print("Duplicated removed ")

Duplicated removed

In [578]:
print("duplicated values are removed",df.duplicated().sum())

duplicated values are removed 0

In [579]:
print("Total no. of bike records",df.shape[0])

Total no. of bike records 7324

In [580]:
## missing values check in your data
df.isnull().sum()

bike_name     0
price         0
city          0
kms_driven    0
owner         0
age           0
power         0
brand         0
dtype: int64

In [581]:
## there is no alphaetical or numerical error

In [582]:
df.head()

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha

In [583]:
cat_col =df.select_dtypes(include='O')
cat_col.head()

                              bike_name       city        owner          brand
0    TVS Star City Plus Dual Tone 110cc  Ahmedabad  First Owner            TVS
1           Royal Enfield Classic 350cc      Delhi  First Owner  Royal Enfield
2                  Triumph Daytona 675R      Delhi  First Owner        Triumph
3                  TVS Apache RTR 180cc  Bangalore  First Owner            TVS
4  Yamaha FZ S V 2.0 150cc-Ltd. Edition  Bangalore  First Owner         Yamaha

In [584]:
cat_col = df.select_dtypes(exclude='O')
cat_col.head()

      price  kms_driven  age  power
0   35000.0     17654.0  3.0  110.0
1  119900.0     11000.0  4.0  350.0
2  600000.0       110.0  8.0  675.0
3   65000.0     16329.0  4.0  180.0
4   80000.0     10000.0  3.0  150.0

In [585]:
df['owner'].value_counts()

owner
First Owner             6642
Second Owner             588
Third Owner               84
Fourth Owner Or More      10
Name: count, dtype: int64

In [586]:
dt = {'First Owner': 1,'Second Owner':2,'Third Owner':3,'Fourth Owner Or More':4}

In [587]:
dt

{'First Owner': 1,
 'Second Owner': 2,
 'Third Owner': 3,
 'Fourth Owner Or More': 4}

In [588]:
df['owner'] = df['owner'].map(dt)  # single time execute

In [589]:
df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,1,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,1,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,1,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,1,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,1,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,25000.0,Delhi,48587.0,1,8.0,150.0,Hero
9369,Bajaj Avenger 220cc,35000.0,Bangalore,60000.0,1,9.0,220.0,Bajaj
9370,Harley-Davidson Street 750 ABS,450000.0,Jodhpur,3430.0,1,4.0,750.0,Harley-Davidson
9371,Bajaj Dominar 400 ABS,139000.0,Hyderabad,21300.0,1,4.0,400.0,Bajaj
9372,Bajaj Avenger Street 220,80000.0,Hyderabad,7127.0,1,5.0,220.0,Bajaj

In [590]:
df['brand'].value_counts()

brand
Bajaj              2081
Royal Enfield      1346
Hero               1142
Honda               676
Yamaha              651
TVS                 481
KTM                 375
Suzuki              203
Harley-Davidson      91
Kawasaki             61
Hyosung              53
Mahindra             50
Benelli              46
Triumph              21
Ducati               20
BMW                  10
Jawa                  7
Indian                3
MV                    3
Rajdoot               1
LML                   1
Yezdi                 1
Ideal                 1
Name: count, dtype: int64

In [591]:

for i in df['brand'].value_counts():
    if i >= 10:
        print(i)

2081
1346
1142
676
651
481
375
203
91
61
53
50
46
21
20
10

In [592]:
# Using query to filter and print counts
counts = df['brand'].value_counts()
print(counts[counts >= 10])

brand
Bajaj              2081
Royal Enfield      1346
Hero               1142
Honda               676
Yamaha              651
TVS                 481
KTM                 375
Suzuki              203
Harley-Davidson      91
Kawasaki             61
Hyosung              53
Mahindra             50
Benelli              46
Triumph              21
Ducati               20
BMW                  10
Name: count, dtype: int64

In [593]:
bike_brand = list(df['brand'].value_counts().head(16).index)
bike_brand

['Bajaj',
 'Royal Enfield',
 'Hero',
 'Honda',
 'Yamaha',
 'TVS',
 'KTM',
 'Suzuki',
 'Harley-Davidson',
 'Kawasaki',
 'Hyosung',
 'Mahindra',
 'Benelli',
 'Triumph',
 'Ducati',
 'BMW']

In [594]:
df2 = df[df['brand'].isin(bike_brand)]
df2.head()

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,1,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,1,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,1,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,1,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,1,3.0,150.0,Yamaha

In [595]:
df['brand'].value_counts()

brand
Bajaj              2081
Royal Enfield      1346
Hero               1142
Honda               676
Yamaha              651
TVS                 481
KTM                 375
Suzuki              203
Harley-Davidson      91
Kawasaki             61
Hyosung              53
Mahindra             50
Benelli              46
Triumph              21
Ducati               20
BMW                  10
Jawa                  7
Indian                3
MV                    3
Rajdoot               1
LML                   1
Yezdi                 1
Ideal                 1
Name: count, dtype: int64

In [596]:
ls=list(df['brand'].value_counts().keys())
ls

['Bajaj',
 'Royal Enfield',
 'Hero',
 'Honda',
 'Yamaha',
 'TVS',
 'KTM',
 'Suzuki',
 'Harley-Davidson',
 'Kawasaki',
 'Hyosung',
 'Mahindra',
 'Benelli',
 'Triumph',
 'Ducati',
 'BMW',
 'Jawa',
 'Indian',
 'MV',
 'Rajdoot',
 'LML',
 'Yezdi',
 'Ideal']

In [597]:
# for i in range(16):
#     dt[ls[i]]=i

In [598]:
# dt

In [599]:
for i in range(len(df2['brand'].value_counts())):
    dt[ls[i]] = i+1

In [600]:
dt

{'First Owner': 1,
 'Second Owner': 2,
 'Third Owner': 3,
 'Fourth Owner Or More': 4,
 'Bajaj': 1,
 'Royal Enfield': 2,
 'Hero': 3,
 'Honda': 4,
 'Yamaha': 5,
 'TVS': 6,
 'KTM': 7,
 'Suzuki': 8,
 'Harley-Davidson': 9,
 'Kawasaki': 10,
 'Hyosung': 11,
 'Mahindra': 12,
 'Benelli': 13,
 'Triumph': 14,
 'Ducati': 15,
 'BMW': 16}

In [601]:
df2['brand'] = df2['brand'].map(dt)

C:\Users\saini\AppData\Local\Temp\ipykernel_13276\3676136198.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['brand'] = df2['brand'].map(dt)

In [602]:
df2.head()

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,1,3.0,110.0,6
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,1,4.0,350.0,2
2,Triumph Daytona 675R,600000.0,Delhi,110.0,1,8.0,675.0,14
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,1,4.0,180.0,6
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,1,3.0,150.0,5

In [603]:
x = df2.drop('price',axis='columns')   # independents variables 
y = df2[['price']]  # dependent variable or target varible

In [604]:
x.head()

,bike_name,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,Ahmedabad,17654.0,1,3.0,110.0,6
1,Royal Enfield Classic 350cc,Delhi,11000.0,1,4.0,350.0,2
2,Triumph Daytona 675R,Delhi,110.0,1,8.0,675.0,14
3,TVS Apache RTR 180cc,Bangalore,16329.0,1,4.0,180.0,6
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,Bangalore,10000.0,1,3.0,150.0,5

In [605]:
df2.head()

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,1,3.0,110.0,6
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,1,4.0,350.0,2
2,Triumph Daytona 675R,600000.0,Delhi,110.0,1,8.0,675.0,14
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,1,4.0,180.0,6
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,1,3.0,150.0,5

# Splitting data dependent and independent

In [606]:
from sklearn.model_selection import train_test_split

In [607]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)  # test size 20%

In [608]:
# importing linerarregression algorithm class
from sklearn.linear_model import LinearRegression

In [609]:
# instance creation
lnr = LinearRegression()

In [610]:
## Algorithm train
lnr.fit(x_train,y_train)

ValueError: could not convert string to float: 'Royal Enfield Continental GT 535cc'

In [ ]:
## Model evaluation
print("Training score  ",lnr.score(x_train,y_train) * 100)
print("Testing score  ",lnr.score(x_test,y_test) * 100)

ValueError: Input X contains NaN.
LinearRegression does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values

In [ ]:
x_test.shape  
# total 1462

(1462, 7)

In [ ]:
### Prediction or testing phase 


# Overfit condition ==>  Trainig - High   and Testing - Low
# Underfit condition ==>  Trainig - Low   and Testing - High
# Generalized condition ==>  if Training is greater then Testing with 5 number


prediction = lnr.predict(x_test)

ValueError: Input X contains NaN.
LinearRegression does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values

In [ ]:
prediction.shape

NameError: name 'prediction' is not defined

In [ ]:
comparedf = pd.concat([x_test,y_test],axis=1)

In [ ]:
cpmparedf['prediction'] = prediction

NameError: name 'prediction' is not defined

In [ ]:
comparedf.head()

      bike_name  city  kms_driven  owner   age  power  brand     price
6593       84.0     4     14547.0      1   3.0  150.0      8   80000.0
8201        1.0     6     21000.0      1   8.0  350.0      2   95000.0
8505       86.0     4     63000.0      1   9.0  883.0      9  360000.0
7960       24.0     9      6859.0      1   3.0  200.0      7  110000.0
1121       11.0     4     22840.0      1  11.0  350.0      2   65000.0

In [ ]:
comparedf['residual'] = comparedf['price'] - comparedf['prediction']

KeyError: 'prediction'

In [ ]:
comparedf.head()

      bike_name  city  kms_driven  owner   age  power  brand     price
6593       84.0     4     14547.0      1   3.0  150.0      8   80000.0
8201        1.0     6     21000.0      1   8.0  350.0      2   95000.0
8505       86.0     4     63000.0      1   9.0  883.0      9  360000.0
7960       24.0     9      6859.0      1   3.0  200.0      7  110000.0
1121       11.0     4     22840.0      1  11.0  350.0      2   65000.0

In [ ]:
## Prediction for single points
unseen_bike = [[4500,2,3,220,3]]
price_of_unseen_bike = lnr.predict(unseen_bike)
price_of_unseen_bike

c:\Program Files\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

AttributeError: 'LinearRegression' object has no attribute 'coef_'

In [ ]:
x_train

,bike_name,city,kms_driven,owner,age,power,brand
3633,Bajaj Pulsar NS200,Delhi,28000.0,1,9.0,200.0,1
2992,Hero Passion Pro 100cc,Delhi,11237.0,1,9.0,100.0,3
4736,Hero Passion Pro i3S Disc 100cc,Delhi,4610.0,1,3.0,100.0,3
466,Bajaj Discover 100M,Ahmedabad,33000.0,1,7.0,100.0,1
641,Royal Enfield Classic 350cc,Mumbai,20000.0,1,3.0,350.0,2
...,...,...,...,...,...,...,...
7593,Honda Livo 110cc,Faridabad,10909.0,1,5.0,110.0,4
5485,Honda CBR 150R 150cc,Noida,15000.0,1,5.0,150.0,4
5690,Bajaj Discover 125ST,Delhi,45000.0,1,8.0,125.0,1
6282,Royal Enfield Bullet Electra 350cc,Delhi,36000.0,3,11.0,350.0,2
1610,Bajaj Avenger 220cc,Bangalore,7600.0,1,6.0,220.0,1

# Creating folder and its function

In [ ]:
## Saving models 
import os,joblib

In [ ]:
os.makedirs('models',exist_ok=True)

In [ ]:
lnr

sklearn.linear_model._base.LinearRegression

In [ ]:
student_ls = ['mohan','rohan','sohan','manmohan']
student_ls

['mohan', 'rohan', 'sohan', 'manmohan']

In [ ]:
joblib.dump(student_ls,'studentList.lb')

['studentList.lb']

In [ ]:
joblib.load('studentList.lb')  # Reading a file from joblib

['mohan', 'rohan', 'sohan', 'manmohan']

In [ ]:
# Locally added an encrypted file parmanentally
joblib.dump(lnr,'./models/linearRegression.lb')

['./models/linearRegression.lb']

In [ ]:
joblib.load('./models/linearRegression.lb')

LinearRegression()